# SQL Alchemy

## Installation

For this lesson, you must install the libraries `SQLAlchemy` and `PyMySql` on your computers.
There are several ways to do this installation:

### Option 1

- Open a new Jupyter notebook
- Open a new code cell and type:

```shell
!pip install sqlalchemy
```

- Open a new code cell and type:

```shell
!pip install pymysql
```

### Option 2

Alternatively you can go to the `Anaconda navigator`, and click on the `Environments` section on the left panel. Then:

- On the search bar type: `sqlalchemy`
- If this library doesn't appear as installed click on the checkbox and then on `Apply`, accept the `dependencies` and wait until the system installs the library
- On the search bar type: `pymysql`
- If this library doesn't appear as installed click on the checkbox and then on `Apply`, accept the `dependencies` and wait until the system installs the library

### Option 3

❗️ If you use this third option, you will first have to save and close your Jupyter notebook, then run the instructions below and open again the Jupyter notebook.


- Open a new terminal (MacOS/Linux) or Conda prompt and type

```shell
!pip install sqlalchemy
```

- Open a new code cell and type:

```shell
!pip install pymysql
```

### Important Note


**Upgrading to SQLAlchemy Version 2.0**:

The new version 2.0 of SQLAlchemy introduces significant API changes compared to the 1.4 series. Given these changes, it's crucial to ensure you have the latest version installed, especially if you plan to follow along with classes or tutorials that use the newest features of the library.

To get started, follow these steps:

1. **Check Your Current Version**:
   Before making any changes, it's wise to check your currently installed version of SQLAlchemy.
   ```bash
   pip show sqlalchemy | grep Version
   ```

2. **Upgrade to Version 2.0 (if necessary)**:
   If your current version is in the 1.x series instead of 2.x, you should upgrade to the latest version.
   ```bash
   pip install --upgrade sqlalchemy
   ```

In [3]:
pip show sqlalchemy | grep Version

Version: 2.0.51
Note: you may need to restart the kernel to use updated packages.

In [4]:
!pip install --upgrade sqlalchemy

Requirement already satisfied: sqlalchemy in /opt/homebrew/lib/python3.10/site-packages (2.0.51)
Requirement already satisfied: typing-extensions>=4.6.0 in /Users/ricardo.higginson@scalapay.com/Library/Python/3.10/lib/python/site-packages (from sqlalchemy) (4.15.0)

## What is SQL Alchemy

SQLAlchemy is a popular SQL toolkit and Object-Relational Mapping (ORM) library for Python. It provides a set of high-level APIs to connect to relational databases. Using SQLAlchemy, you can work with relational databases in a more Pythonic way, abstracting away many of the common database operations. Here's a breakdown of its main features:

1. **ORM (Object-Relational Mapping)**:
   - Allows classes to be mapped to database tables, so you can use Python objects to represent database rows.
   - Provides a high-level, abstracted pattern for CRUD (Create, Read, Update, Delete) operations.
   - Automates the process of synchronizing object states with database content.

2. **SQL Expression Language**:
   - A comprehensive SQL abstraction tool that allows you to build SQL queries using Python expressions.
   - Gives you the power and flexibility of raw SQL, but in a more Pythonic way.

3. **Engine**:
   - Provides a source of connectivity to a database, which can be fine-tuned for the specific database dialect.
   - Manages connection pooling, which is crucial for scalable applications.

4. **Dialects**:
   - SQLAlchemy supports a variety of database backends by using dialects. Commonly used database systems like PostgreSQL, MySQL, SQLite, and Oracle have their own dialects in SQLAlchemy.

5. **Schema and Types**:
   - SQLAlchemy provides a way to declare table structures and relationships directly in Python, which can then be used to automatically create (or drop) database structures.
   - Offers a broad set of SQL standard and vendor-specific datatypes.

6. **Session**:
   - Manages the persistence operations for ORM-mapped objects.
   - Acts as a transactional buffer, accumulating changes and flushing them to the database in a batch.

## Creating the engine

**Connecting to a Database using SQLAlchemy**:

To connect to a database, we need to set up an SQLAlchemy "engine". Think of this engine as a bridge or gateway between your Python application and the actual database.

The SQLAlchemy engine provides a standard way to interact with the database and execute SQL statements. It achieves this by managing a set of database connections and using a "dialect" specific to your database.

To get an engine, we use:

```python
sqlalchemy.create_engine(connection_string)
```

To create the *connection string*, this is the general syntax **`'dialect+driver://username:password@host:port/database'`**

In [1]:
import pandas as pd
import numpy as np
import pymysql
from sqlalchemy import create_engine
import getpass  # To get the password without showing the input

# Note that when you use _SQLAlchemy_ and establish the connection, you do not even need to be logged in Sequel Pro or MySQL Workbench.

In [2]:
password = 'R10a30h1991!' #your SQL password as a string

In [3]:
bd = "lab_mysql"
connection_string = 'mysql+pymysql://root:' + password + '@localhost/'+bd
engine = create_engine(connection_string)
engine

Engine(mysql+pymysql://root:***@localhost/lab_mysql)

This password policy is used only for illustrative purposes and to be simple. However, we shouldn't store the password in the Jupyter notebook variable. There are other safer ways to do this as shown [here](https://towardsdatascience.com/keeping-credentials-safe-in-jupyter-notebooks-fbd215a8e311) and [here](https://dadoverflow.com/2019/08/09/how-do-you-hide-secrets-in-jupyter-notebooks/)

## Getting a connection

We get a connection using the `connect()` method.

```python
connection = engine.connect()
```

It's better practice though to use context managers to manage the connect/release process:

```python
with engine.connect() as connection:
    ...

```

## Running queries

The SQLAlchemy Connection features an `.execute()` method that will run queries.

```python
with engine.connect() as connection:
    connection.execute(...)
    ...

```

The `Connection.execute()` always returns a `sqlalchemy.engine.Result` object.

### Running Raw Queries

To invoke a textual query, use the `sqlalchemy.text()` passed to `.execute()`.

In [4]:
from sqlalchemy import text

In this specific case the `Result` its called `CursorResult`.

The `Result` object has many methods we can use. Let's look at some of them.

In [5]:
# We can also get it as a DataFrame

with engine.connect() as connection:
    query = text('SELECT * FROM cars')
    result = connection.execute(query)
    df = pd.DataFrame(result.all())

df

                 vin manufacturer              model  year   color
0  3K096I98581DHSNUP   Volkswagen             Tiguan  2019    Blue
1  DAM41UDN3CHU2WVF6        Volvo                V60  2019    Gray
2  DAM41UDN3CHU2WVF7        Volvo  V60 Cross Country  2019    Gray
3  HKNDGS7CU31E9Z7JW       Toyota               RAV4  2018  Silver
4  RKXVNNIHLVVZOUB4M         Ford             Fusion  2018   White
5  ZM8G7BEUQZ97IH46V      Peugeot             Rifter  2019     Red

In [6]:
lista_tuplas = list(df.itertuples(index=False, name=None))
lista_tuplas

[('3K096I98581DHSNUP', 'Volkswagen', 'Tiguan', 2019, 'Blue'),
 ('DAM41UDN3CHU2WVF6', 'Volvo', 'V60', 2019, 'Gray'),
 ('DAM41UDN3CHU2WVF7', 'Volvo', 'V60 Cross Country', 2019, 'Gray'),
 ('HKNDGS7CU31E9Z7JW', 'Toyota', 'RAV4', 2018, 'Silver'),
 ('RKXVNNIHLVVZOUB4M', 'Ford', 'Fusion', 2018, 'White'),
 ('ZM8G7BEUQZ97IH46V', 'Peugeot', 'Rifter', 2019, 'Red')]

## Summary

As you can see, launching queries from Python against a SQL database involves several steps:

- Create the `engine`:
    ```python
    connection_string = 'dialect+driver://username:password@host:port/database'
    engine = sqlalchemy.create_engine(connection_string)
    ```
- Getting a `connection`
    ```python
    with engine.connect() as connection:
        ...
    ```
- Create a string with the query and put it inside `text()` method
- Launch the query with `execute()` method
- Get data from the Result object as needed

For example, if we want the whole result from our `SELECT` query, we could do:

```python
with engine.connect() as connection:    
    query = text('SELECT ...')
    result = connection.execute(query)
    df = pd.DataFrame(result.all())
    
df # Do stuff with the DataFrame
```


Some guidelines when creating functions:

- Try to make your functions as self contained as possible
- Try to make your functions as general as possible (use optional arguments if needed)
- Test your Python functions!

# Bonus: MySQL Connector

MySQL Connector/Python is an official MySQL client library for Python. It allows Python programs to connect and interact with MySQL databases.

- Suitable for scripts or applications that need a straightforward way to connect to a MySQL database and execute queries.
- Specific to MySQL.
- Focused on providing a direct connection to MySQL, so while it's efficient for that purpose, it lacks the broader features and abstractions of an ORM like SQL Alchemy.
- Operates at a lower level. You work directly with SQL queries, and the results you get back are typically in the form of rows and columns, rather than structured Python objects.


## Installation:
Before we start, ensure you have `mysql-connector-python` installed:
```bash
pip install mysql-connector-python
```

In [ ]:
%pip install mysql-connector-python

## Establishing a Connection:
To connect to a MySQL database, you need the host name (or IP address), the database name, and the credentials (username and password).

```python
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="your_username",
    password="your_password",
    database="your_database_name"
)
```

In [7]:
import mysql.connector

In [8]:
import getpass  # To get the password without showing the input
password = getpass.getpass()

In [9]:
conn = mysql.connector.connect(host='localhost',
                        user='root',
                        passwd=password)

## Creating a Cursor:
A cursor object allows you to execute SQL queries and fetch results.

```python
cursor = conn.cursor()
```

In [10]:
cursor = conn.cursor()

cursor

## Executing SQL Queries:
Using the cursor, you can execute any SQL statement.

**SELECT Statement:**

```python
cursor.execute("SELECT * FROM your_table_name")
rows = cursor.fetchall()

for row in rows:
    print(row)
```

**INSERT Statement:**

```python
sql = "INSERT INTO your_table_name (column1, column2) VALUES (%s, %s)"
values = ("value1", "value2")

cursor.execute(sql, values)
conn.commit()  # Save the changes
```

**CREATE Statement:**
```python
cursor.execute("CREATE DATABASE new_database_name")
conn.commit()  # Save the changes
```

### Example: CoffeeShop DB 📒☕

We're going to use a simple, relatable example: setting up a database for a coffee shop.

1. **Create** our `CoffeeShop` database.
2. **Create** a table to list various coffee items (coffee id, coffee name, price).
3. **Insert** coffee menu items into our table.
4. **Query** our table to view the items we've added.

Let's create a CoffeeShop database.

In [11]:
# Create CoffeeShop Database
cursor.execute("CREATE DATABASE IF NOT EXISTS CoffeeShop")

In [12]:
# Switch to the CoffeeShop Database
cursor.execute("USE CoffeeShop")

Create a Menu Table: We'll create a table called Menu with columns for coffee name and its price.

In [13]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS Menu (
    coffee_id INT AUTO_INCREMENT PRIMARY KEY,
    coffee_name VARCHAR(255) NOT NULL,
    price DECIMAL(5,2) NOT NULL
)
""")
print("Table Menu created successfully!")

Table Menu created successfully!

Let's insert values into the table:

In [14]:
# Insert Coffee Items into Menu Table
menu_items = [
    ("Espresso", 2.50),
    ("Cappuccino", 3.00),
    ("Latte", 3.50),
    ("Americano", 2.00),
    ("Mocha", 3.75)
]

cursor.executemany("INSERT INTO Menu (coffee_name, price) VALUES (%s, %s)", menu_items)
conn.commit()
print(f"{cursor.rowcount} coffee items inserted!")

5 coffee items inserted!

Finally, lets see our data!

In [15]:
# Select and Display Coffee Items from Menu Table
cursor.execute("SELECT coffee_name, price FROM Menu ORDER BY price DESC")
results = cursor.fetchall()

pd.DataFrame(results)

            0     1
0       Mocha  3.75
1       Latte  3.50
2  Cappuccino  3.00
3    Espresso  2.50
4   Americano  2.00

## Closing the Connection:
After performing database operations, remember to close the cursor and the connection.

```python
cursor.close()
conn.close()
```

In [16]:
# Close the cursor and the connection.
cursor.close()
conn.close()